[package]
name = "spark-client"
version.workspace = true
edition.workspace = true

[[bin]]
name = "spark"
path = "src/main.rs"

[dependencies]
spark-model = { path = "../spark-model" }
spark-ui = { path = "../spark-ui" }
spark-transport = { path = "../spark-transport" }
spark-terminal = { path = "../spark-terminal" }
gpui = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
